-- MySQL Script generated by MySQL Workbench
-- 07/24/15 02:27:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Table `produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produtos` (
  `id` INT NOT NULL auto_increment COMMENT '',
  `codigo` INT NOT NULL COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `quantidade` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC)  COMMENT '');
  
  
  